# Тестирование утилиты pcli из командной строки с помощью фреймворка Click
version: 0.2
phases:
  install:
    commands:
    - echo "Upgrade Pip and install packages"
    - pip install --upgrade pip
    - make install
    # Создаем каталог aws
    - mkdir -р ~/.aws/
    # Создаем файл с фиктивными учетными данными
    - echo "[default]\naws_access_key_id = \
    FakeKey\naws_secret_access_key = \
    FakeKey\naws_session_token = FakeKey" >\
    ~/.aws/credentials

  build:
    commands:
      - echo "Run lint and test"
      - make lint
      - PYTHONPATH=".";make test
  post_build:
    commands:
      - echo Build completed on 'date'